name: Direct review
on:
  workflow_dispatch:
    inputs:
      baseref:
        required: true
      headref:
        required: true

  
permissions:
  contents: write
  # Note that this permission will not be available if the PR is from a forked repository

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
    - name: Perform dependency review
      uses: actions/dependency-review-action@v3
      with:
        base-ref: ${{ inputs.baseref }}
        head-ref: ${{ inputs.headref }}
