name: PR check
on:
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup Gradle to generate dependency graphs
      uses: gradle/gradle-build-action@dd/dependency-review-support
      with:
        dependency-graph: generate
    - name: Run a build and generate the dependency graph which will be submitted post-job
      run: ./gradlew build
